In [1]:
import numpy as np

In [99]:
iteraciones=10000
nDados=5
dados = np.random.randint(1,6,size=(iteraciones,nDados))
cant3 = np.array([np.count_nonzero(i==3) for i in dados])
hist = np.histogram(cant3, bins=6, range=(0,6))
hist

(array([3216, 4098, 2067,  537,   77,    5], dtype=int64),
 array([0., 1., 2., 3., 4., 5., 6.]))

In [108]:
from scipy.stats import binom

binomPosta = binom.pmf(k=range(6), n=5, p=1/6)
binomPosta


array([4.01877572e-01, 4.01877572e-01, 1.60751029e-01, 3.21502058e-02,
       3.21502058e-03, 1.28600823e-04])

In [105]:
binom.pmf(k=range(6), n=5, p=1/6)

array([4.01877572e-01, 4.01877572e-01, 1.60751029e-01, 3.21502058e-02,
       3.21502058e-03, 1.28600823e-04])